### ISSUE TITLE
pip installation is failing 

### ISSUE THREAD

**Issue by Niarch** [jitsi/asr-wer#14]
```
Collecting jiwer
  Downloading https://files.pythonhosted.org/packages/c7/fd/88639901195f2625941efdf2a1496c540b3390149
9a986fb271af28e4436/jiwer-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sausharma/temp/pip-build-sMieMl/jiwer/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/sausharma/temp/pip-build-sMieMl/
jiwer/
```

**Comment by Niarch** [comment]
ooh so it required python3, dependency isn't mentioned anywhere
Closing the issue
